baseURL = "https://lokal.ninja/niedersachsen"
languageCode = "de-DE"
title = "Lokal Ninja - Niedersachsen"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Niedersachsen"
  repo = "niedersachsen"
